"""preview_image_url

Revision ID: 77e9b96c7948
Revises: e74e2884d915
Create Date: 2025-10-15 13:45:55.454665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e9b96c7948'
down_revision = 'e74e2884d915'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_items_cart_id_fkey', 'cart_items', type_='foreignkey')
    op.drop_constraint('cart_items_product_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'])
    op.drop_constraint('carts_user_id_fkey', 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.drop_constraint('orders_promo_code_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'promo_codes', ['promo_code_id'], ['id'])
    op.create_index(op.f('ix_preorder_statuses_id'), 'preorder_statuses', ['id'], unique=False)
    op.drop_constraint('preorder_statuses_wave_id_fkey', 'preorder_statuses', type_='foreignkey')
    op.drop_constraint('preorder_statuses_order_id_fkey', 'preorder_statuses', type_='foreignkey')
    op.create_foreign_key(None, 'preorder_statuses', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'preorder_statuses', 'preorder_waves', ['wave_id'], ['id'])
    op.create_index(op.f('ix_preorder_waves_id'), 'preorder_waves', ['id'], unique=False)
    op.drop_constraint('preorder_waves_product_id_fkey', 'preorder_waves', type_='foreignkey')
    op.create_foreign_key(None, 'preorder_waves', 'products', ['product_id'], ['id'])
    op.create_index(op.f('ix_product_media_id'), 'product_media', ['id'], unique=False)
    op.drop_constraint('product_media_product_id_fkey', 'product_media', type_='foreignkey')
    op.create_foreign_key(None, 'product_media', 'products', ['product_id'], ['id'])
    op.add_column('products', sa.Column('preview_image_url', sa.String(length=500), nullable=True))
    op.drop_constraint('promo_code_products_product_id_fkey', 'promo_code_products', type_='foreignkey')
    op.drop_constraint('promo_code_products_promo_code_id_fkey', 'promo_code_products', type_='foreignkey')
    op.create_foreign_key(None, 'promo_code_products', 'promo_codes', ['promo_code_id'], ['id'])
    op.create_foreign_key(None, 'promo_code_products', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promo_code_products', type_='foreignkey')
    op.drop_constraint(None, 'promo_code_products', type_='foreignkey')
    op.create_foreign_key('promo_code_products_promo_code_id_fkey', 'promo_code_products', 'promo_codes', ['promo_code_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('promo_code_products_product_id_fkey', 'promo_code_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'preview_image_url')
    op.drop_constraint(None, 'product_media', type_='foreignkey')
    op.create_foreign_key('product_media_product_id_fkey', 'product_media', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_product_media_id'), table_name='product_media')
    op.drop_constraint(None, 'preorder_waves', type_='foreignkey')
    op.create_foreign_key('preorder_waves_product_id_fkey', 'preorder_waves', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_preorder_waves_id'), table_name='preorder_waves')
    op.drop_constraint(None, 'preorder_statuses', type_='foreignkey')
    op.drop_constraint(None, 'preorder_statuses', type_='foreignkey')
    op.create_foreign_key('preorder_statuses_order_id_fkey', 'preorder_statuses', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('preorder_statuses_wave_id_fkey', 'preorder_statuses', 'preorder_waves', ['wave_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_preorder_statuses_id'), table_name='preorder_statuses')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('orders_promo_code_id_fkey', 'orders', 'promo_codes', ['promo_code_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key('carts_user_id_fkey', 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_product_id_fkey', 'cart_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('cart_items_cart_id_fkey', 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
